YCDOCIO-3558: Updated Terraform manifest
yandex-cloud-examples/yc-data-transfer-from-on-premise-mysql-to-cloud pull request #1
Opened 2024-04-24 18:40 UTC by Nadezhda-Subotka

https://st.yandex-team.ru/YCDOCIO-3558

Updated Terraform manifest.

2024-04-27 07:32 UTC, voloschuk-fedor requested changes

2024-04-27 07:32 UTC, voloschuk-fedor commented on data-transfer-mysql-mmy.tf
> +  mysql_target_endpoint_name = "mysql-source"                                   # Name of the target endpoint for the MySQL cluster
Здесь что-то не так, параметр и его описание — target, значение параметра — source.
По идее, здесь должен быть везде source, раз это сторонний кластер MySQL, выступающий в роли источника.

2024-04-27 07:32 UTC, voloschuk-fedor commented on data-transfer-mysql-mmy.tf
> +  name        = local.mysql_target_endpoint_name
Здесь тоже нужно будет поправить.

2024-04-27 12:16 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
> +  mysql_target_endpoint_name = "mysql-source"                                   # Name of the target endpoint for the MySQL cluster
Да, здесь должно быть source. Исправила.

2024-04-27 12:16 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
> +  name        = local.mysql_target_endpoint_name
Исправила.

2024-04-27 15:40 UTC, alena-linki requested changes
Ревью англ. текстов

2024-04-27 15:40 UTC, alena-linki commented on data-transfer-mysql-mmy.tf
> +# Set source and target clusters settings
```suggestion
# Configure the parameters of the source and target clusters
```

Несколько проблем:

- "Set settings" — однокоренное, нужен синоним.
- Когда у тебя идут формулировки вида "<объект в мн. числе> <сущ.>", первое слово обычно ставится в ед. числе. Из-за этого может быть непонятно, что имеется в виду несколько объектов. Поэтому порядок слов лучше поменять.
- Нужны артикли.

2024-04-27 15:40 UTC, alena-linki commented on data-transfer-mysql-mmy.tf
> +  source_user    = ""   # Set the source cluster username
Тот же [комментарий про слово "set"](https://github.com/yandex-cloud/examples/pull/255#discussion_r1581843386)

2024-04-27 15:40 UTC, alena-linki commented on data-transfer-mysql-mmy.tf
> +  source_host    = ""   # Set the source cluster master host IP address or FQDN
```suggestion
  source_host    = ""   # IP address or FQDN of the master host in the source cluster
```
Слишком длинная цепочка сущ-ных, ничего непонятно

2024-04-27 15:40 UTC, alena-linki commented on data-transfer-mysql-mmy.tf
> +  source_port    = 3306 # Set the source cluster port number that Data Transfer will use for connections
Здесь последовательность слов, думаю, лучше сохранить, потому что "that" относится к порту. Только "set" желательно убрать.

2024-04-27 15:40 UTC, alena-linki commented on data-transfer-mysql-mmy.tf
>    description = "Source endpoint for MySQL cluster"
```suggestion
  description = "Source endpoint for the MySQL cluster"
```

2024-04-27 15:40 UTC, alena-linki commented on data-transfer-mysql-mmy.tf
>    description = "Transfer from MySQL cluster to the Managed Service for MySQL cluster"
```suggestion
  description = "Transfer from the MySQL cluster to the Managed Service for MySQL cluster"
```

2024-05-13 15:27 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
> +# Set source and target clusters settings
Исправила.

2024-05-13 15:30 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
> +  source_user    = ""   # Set the source cluster username
Убрала "set".

2024-05-13 15:32 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
> +  source_host    = ""   # Set the source cluster master host IP address or FQDN
Исправила.

2024-05-13 15:33 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
>    description = "Source endpoint for MySQL cluster"
Исправила.

2024-05-13 15:34 UTC, Nadezhda-Subotka commented on data-transfer-mysql-mmy.tf
>    description = "Transfer from MySQL cluster to the Managed Service for MySQL cluster"
Исправила.

2024-05-16 08:14 UTC, alena-linki approved these changes

2024-05-23 11:35 UTC, lanieuszko approved these changes

2024-05-23 11:35 UTC, merged